### ISSUE TITLE
Any usage examples?

### ISSUE THREAD

**Issue by kingfisher09** [cadouthat/pico-dshot#2]
Hi, Sorry if this is a very basic question but I am wanting to use this library to control a robot from an Arduino Nano rp2040 Connect. Do you have any examples of your library in use that I could base my code on?

Thanks,

**Comment by cadouthat** [comment]
I don't have any examples currently in the repo (I'm using this in a private repo for a flight controller), but the usage is pretty simple

```
DShotEncoder enc(0); // rp2040 GPIO 0
enc.init(true); // true for auto-repeat (read warning in dshot_encoder.h about why this may be unsafe)
enc.sendThrottle(0);
sleep_ms(3000); // wait for ESC arming
enc.sendThrottle(0.5); // start motor
sleep_ms(500);
enc.stop(); // stop motor
```
